/** 单发文档计划模型调用：prompt 组装 + 一次模型调用返回原始响应。 */
import fs from 'fs'
import log from 'electron-log/main.js'
import { extractModelText, resolveModel } from '../agent-runtime/model'
import type { ModelRuntimeConfig } from '../agent-runtime/model'
import { resolveModelTimeoutMs } from '@shared/model-timeout'
import { formatDocumentOutlineScanForPrompt, type DocumentOutlinePageCandidate, type DocumentOutlineScan } from './document-outline-scan'
import type { PreparedSourceFile } from './document-source-preparation'
import {
  MAX_PAGE_COUNT,
  MAX_PARSE_SOURCE_PREVIEW_CHARS,
  formatLightweightPageCandidateSkeletonForPrompt,
  hasOutlinePageCandidateSkeleton
} from './document-plan-quality'

const buildSingleShotDocumentPlanPrompt = (args: {
  topic: string
  existingBrief: string
  file: PreparedSourceFile
  outlineScan: DocumentOutlineScan | null
  pageCandidates: DocumentOutlinePageCandidate[]
  sourcePreview: string
  sourcePreviewLimit: number
  sourcePreviewTruncated: boolean
  retryHint?: string
}): string => {
  const useLightweightSourcePlan = hasOutlinePageCandidateSkeleton(args.pageCandidates)

  return [
    'Turn the uploaded document into the fixed JSON needed by the PPT creation form.',
    'This is a single-shot document parsing task. The host already scanned the source document with Markdown/GFM AST when possible.',
    'Do not ask to read the file, do not mention tools, and do not reconstruct the source document.',
    useLightweightSourcePlan
      ? 'Use the page candidate skeleton as the authoritative outline. Do not need source body text during parsing; later slide generation will read source passages by line range.'
      : 'No authoritative page candidate skeleton is available. Use the bounded source preview and any structure scan to infer a concise source-ordered page outline.',
    '',
    'Return only a JSON object. Do not return Markdown, explanations, or extra fields.',
    useLightweightSourcePlan
      ? 'Use exactly these fields: topic, pageCount. Do not include briefText.'
      : 'Use exactly these fields: topic, pageCount, briefText.',
    '',
    'Output language rules:',
    '- Use the dominant language of the source structure, user topic, and existing brief.',
    useLightweightSourcePlan
      ? ''
      : '- If the source structure is primarily Chinese, use Chinese labels in briefText.',
    useLightweightSourcePlan
      ? ''
      : '- If the source structure is primarily English, use English labels in briefText.',
    '- Keep proper nouns, product names, technical terms, quoted text, and metrics in their original form when appropriate.',
    '',
    'Field rules:',
    '- topic: a concise title suitable for the creation form topic input.',
    `- pageCount: an integer from 1 to ${MAX_PAGE_COUNT}.`,
    useLightweightSourcePlan
      ? '- Return pageCount equal to the page candidate skeleton count.'
      : '- Infer pageCount from source structure, information density, paragraphs, lists, tables, and semantic transitions. Do not return 1 for ordinary multi-section documents.',
    useLightweightSourcePlan
      ? '- Per-page summaries are generated by a later batch pass using source line ranges. Do not write any outline or page summaries now.'
      : '- briefText: a compact page skeleton, not a detailed fact summary.',
    useLightweightSourcePlan
      ? ''
      : '- briefText must include source document structure, recommended outline, and per-page points.',
    useLightweightSourcePlan
      ? ''
      : '- Recommended outline must contain exactly pageCount numbered items.',
    useLightweightSourcePlan
      ? ''
      : '- Per-page points must contain exactly pageCount page entries.',
    useLightweightSourcePlan
      ? ''
      : '- Each page entry should include: page title, page role, source anchor when available, and one short page purpose.',
    '- Do not write detailed facts, metrics, scripts, examples, risks, or per-page summaries during parsing. Later slide generation will inspect source passages again.',
    '- Preserve source order and hierarchy. Do not rewrite the source into a generic storyline, marketing narrative, consulting framework, or inspirational theme.',
    '- Keep chapter divider slides as standalone section-divider pages and include a role marker such as 页面角色：章节页 or Page role: chapter divider.',
    '- Do not add agenda/background/outlook/summary/next-step pages unless present in the source skeleton or requested by the user.',
    '',
    args.outlineScan ? 'Host-provided document structure:' : '',
    args.outlineScan
      ? useLightweightSourcePlan
        ? formatLightweightPageCandidateSkeletonForPrompt({
            scan: args.outlineScan,
            pageCandidates: args.pageCandidates
          })
        : formatDocumentOutlineScanForPrompt(args.outlineScan, args.pageCandidates)
      : '',
    '',
    args.sourcePreview ? 'Bounded source preview for unstructured parsing:' : '',
    args.sourcePreviewTruncated
      ? `The preview is capped at ${args.sourcePreviewLimit} characters. Use it conservatively with the structure scan; do not invent unsupported later-section details.`
      : '',
    args.sourcePreview ? '```text' : '',
    args.sourcePreview,
    args.sourcePreview ? '```' : '',
    args.retryHint
      ? useLightweightSourcePlan
        ? `\nRetry requirement: the previous output failed validation because: ${args.retryHint}. Fix this issue. Return topic and pageCount only, with pageCount exactly matching the page candidate skeleton.`
        : `\nRetry requirement: the previous output failed validation because: ${args.retryHint}. Fix this issue. Ensure briefText is non-empty and pageCount exactly matches the page-level outline and per-page points.`
      : '',
    args.topic
      ? `\nUser-provided topic: ${args.topic}`
      : '\nThe user did not provide a topic; infer it from the document structure.',
    args.existingBrief ? `\nExisting user brief:\n${args.existingBrief}` : '',
    `\nSource document path for later generation only: ${args.file.virtualPath}`,
    '',
    'Return format examples:',
    useLightweightSourcePlan
      ? '{"topic":"直播与短视频自然流增长：汽车经销商新媒体实战指南","pageCount":65}'
      : '',
    useLightweightSourcePlan
      ? ''
      : 'For Chinese source: {"topic":"直播与短视频自然流增长——汽车经销商新媒体实战指南","pageCount":65,"briefText":"演示目标：...\\n源文档结构：...\\n建议大纲：\\n1. 手册结构导航\\n2. 阅读角色指引\\n每页要点：\\n第 1 页：手册结构导航\\n页面角色：内容页\\n来源标题：### 手册结构导航\\n来源范围：lines 17-32\\n页面目的：说明本手册的结构导航。"}',
    useLightweightSourcePlan
      ? ''
      : 'For English source: {"topic":"Product Launch Readiness Review","pageCount":8,"briefText":"Presentation goal: ...\\nSource document structure: ...\\nRecommended outline:\\n1. Launch Readiness\\nPer-page points:\\nPage 1: Launch Readiness\\nPage role: content\\nSource heading: ## Launch Readiness\\nSource range: lines 10-32\\nPage purpose: Anchor the launch readiness section."}'
  ].join('\n')
}

export const runSingleShotDocumentPlanModel = async (args: {
  provider: string
  apiKey: string
  model: string
  baseUrl: string
  maxTokens: number | undefined
  modelRuntime: ModelRuntimeConfig
  modelTimeoutMs: number
  file: PreparedSourceFile
  outlineScan: DocumentOutlineScan | null
  pageCandidates: DocumentOutlinePageCandidate[]
  topic: string
  existingBrief: string
  retryHint?: string
}): Promise<string> => {
  const client = resolveModel(
    args.provider,
    args.apiKey,
    args.model,
    args.baseUrl,
    0.2,
    args.maxTokens,
    args.modelRuntime
  )
  const sourceText = await fs.promises.readFile(args.file.workspacePath, 'utf-8')
  const pageCandidateCount = args.pageCandidates.length
  const useLightweightSourcePlan = hasOutlinePageCandidateSkeleton(args.pageCandidates)
  const sourcePreview = useLightweightSourcePlan
    ? ''
    : sourceText.slice(0, MAX_PARSE_SOURCE_PREVIEW_CHARS)
  const sourcePreviewTruncated =
    !useLightweightSourcePlan && sourceText.length > sourcePreview.length
  const prompt = buildSingleShotDocumentPlanPrompt({
    topic: args.topic,
    existingBrief: args.existingBrief,
    file: args.file,
    outlineScan: args.outlineScan,
    pageCandidates: args.pageCandidates,
    sourcePreview,
    sourcePreviewLimit: MAX_PARSE_SOURCE_PREVIEW_CHARS,
    sourcePreviewTruncated,
    retryHint: args.retryHint
  })
  log.info('[documents:parsePlan] single-shot model invoke', {
    sourceVirtualPath: args.file.virtualPath,
    headingCount: args.outlineScan?.headingCount ?? 0,
    pageCandidateCount,
    sourceLength: sourceText.length,
    sourcePreviewLength: sourcePreview.length,
    sourcePreviewTruncated,
    promptLength: prompt.length
  })
  const result = await client.invoke(
    [
      {
        role: 'system' as const,
        content: useLightweightSourcePlan
          ? 'You are a document-to-PPT-creation-form parser. You have no filesystem tools in this call. Use the host-provided structure scan. Return strict JSON only: topic, pageCount.'
          : 'You are a document-to-PPT-creation-form parser. You have no filesystem tools in this call. Use the host-provided structure scan and any bounded source preview. Return strict JSON only: topic, pageCount, briefText.'
      },
      {
        role: 'user' as const,
        content: prompt
      }
    ],
    {
      signal: AbortSignal.timeout(resolveModelTimeoutMs(args.modelTimeoutMs, 'document'))
    }
  )
  return extractModelText(result)
}
