import { describe, expect, it } from 'vitest'
import { buildPlanningUserPrompt } from '../../../src/main/agent-runtime/prompt/composers/runtime-user'
import { UNIVERSAL_LAYOUTS } from '@shared/universal-layouts'

describe('buildPlanningUserPrompt image policy guidance', () => {
  const baseArgs = {
    topic: '小马宝莉：星光熠熠角色介绍',
    totalPages: 6,
    userMessage: '加一些图片，不要生成图片，用占位图'
  }

  it('omits image guidance when no image policy is set', () => {
    const prompt = buildPlanningUserPrompt(baseArgs)
    expect(prompt).not.toContain('Image requirement (hard)')
  })

  it('tells the planner to pick image-slot layouts in placeholder mode', () => {
    const prompt = buildPlanningUserPrompt({ ...baseArgs, imagePolicy: 'placeholder' })
    expect(prompt).toContain('Image requirement (hard)')
    // 明确图槽只有带 image-slot 的 layoutId 才会有占位图
    expect(prompt).toContain(
      'a text-only layoutId means this slide gets NO image at all'
    )
    // 必须列出目录里真实存在的带图槽 layoutId，planner 才能照选
    const imageLayoutIds = UNIVERSAL_LAYOUTS.filter((layout) => layout.imageCount > 0).map(
      (layout) => layout.id
    )
    for (const id of imageLayoutIds) {
      expect(prompt).toContain(id)
    }
    expect(prompt).toContain('replaceable placeholder frames')
  })

  it('describes ai image mode without the placeholder wording', () => {
    const prompt = buildPlanningUserPrompt({ ...baseArgs, imagePolicy: 'ai' })
    expect(prompt).toContain('Image requirement (hard)')
    expect(prompt).toContain('generated by an image model')
    expect(prompt).not.toContain('replaceable placeholder frames')
  })
})
