/**
 * 方法信号门禁（改编自 ppt-master 的 P01 gate「方法级偏差」分类）：
 * 当同类错误在多页/多次尝试中反复出现，说明不是单页的偶然失误而是生成
 * 方法出了偏差。此时把该类错误的预防性修正注入后续所有页面的提示词，
 * 让后续页主动避开，而不是每页都栽进同一个坑再靠页内重试自救。
 */

export interface PageMethodSignal {
  signalClass: string
  fix: string
}

const SIGNAL_RULES: Array<{ re: RegExp; signal: PageMethodSignal }> = [
  {
    re: /质量校验未通过|harness-quality|emoji-as-icon|padding-below-floor|font-below-floor|unknown-icon-id/i,
    signal: {
      signalClass: 'harness-quality',
      fix: 'Icons must be referenced as <svg data-icon="id"> (never emoji, never hand-written paths), horizontal padding of the content root must meet the canvas floor (px-24+ on 1600px-wide canvases; no px-10/px-12/px-16/px-20), and every explicit font size (text-[Npx] or Tailwind size utilities) must respect the canvas floor — body text ≥18px and headings ≥24px on 1600×900, scaled by canvas height otherwise; auxiliary small text (footer/annotation/source) must live inside footer/small/figcaption or carry data-ppt-text-role="auxiliary" and stay ≥12px.'
    }
  },
  {
    re: /模板骨架|template-skeleton|背景\/装饰资源|skeleton resource/i,
    signal: {
      signalClass: 'template-skeleton',
      fix: 'Reread the template page before writing and carry every background/texture/decorative layer and its local asset path into the fragment; text/data replacement must never strip the visual shell.'
    }
  },
  {
    re: /chart|PPT\.createChart/i,
    signal: {
      signalClass: 'chart-usage',
      fix: 'Charts must follow the amy-ppt-chart skill: read the skill first, wrap PPT.createChart in a DOMContentLoaded listener, and make the @ppt-chart-height marker match the h-[Npx] class.'
    }
  },
  {
    re: /页面未写入|没有成功调用|not written|update_single_page_file|update_template_page_file|占位内容|placeholder page/i,
    signal: {
      signalClass: 'page-not-written',
      fix: 'The page is only generated by successfully calling the write tool with the full creative fragment; describing the HTML in the final response without the tool call always fails.'
    }
  },
  {
    re: /HTML 验证失败|未闭合|开闭标签|unclosed|malformed/i,
    signal: {
      signalClass: 'html-structure',
      fix: 'Write flatter fragments (one root div, grid/flex direct children, ≤4 nesting levels) and self-check that every tag is closed before calling the write tool.'
    }
  },
  {
    re: /溢出|超出画布|overflow|collision|碰撞|遮挡/i,
    signal: {
      signalClass: 'overflow',
      fix: 'Sum the module heights against the canvas budget before writing; when content risks overflow, compress and merge modules first instead of shrinking fonts or letting elements collide.'
    }
  },
  {
    re: /PPT 背景图约束|deck-background|background constraint/i,
    signal: {
      signalClass: 'deck-background',
      fix: 'The assigned full-canvas background <img data-role="deck-background"> must be the first child of the creative root, absolutely positioned behind everything, with text confined to its declared safe area.'
    }
  }
]

/** 从页面失败信息中识别可升级为方法级修正的信号；无法归类时返回 null。 */
export const classifyPageMethodSignal = (errorMessage: string): PageMethodSignal | null => {
  const message = String(errorMessage || '')
  if (!message) return null
  for (const rule of SIGNAL_RULES) {
    if (rule.re.test(message)) return rule.signal
  }
  return null
}
