import {
  CONTENT_LANGUAGE_RULES,
  SOURCE_MATERIAL_PLANNING_RULES,
  STABLE_HTML_FRAGMENT_PROTOCOL
} from "./shared";
import type { DeckEditScope, ImagePolicy, SelectedElementRuntimeContext } from '@shared/generation'
import { formatVisualElementGuidance, type VisualElementPreferences } from '@shared/generation'
import { UNIVERSAL_LAYOUTS } from '@shared/universal-layouts'
import { INDEX_TRANSITION_TYPES } from "../../../../shared/index-transition";
import { formatSelectedElementRuntimeContext } from '../selected-element-context'

const hasSourceMaterialCue = (value: string): boolean =>
  /参考文档|源文档|参考资料|源资料|解析.*大纲|建议大纲|每页要点|必须保留|reference[-\s]?document|source[-\s]?document|source[-\s]?material|recommended outline|per-page points|facts\/metrics/i.test(
    value
  );

/** 按图片槽数量归组目录 ID，供规划 prompt 告诉 planner 哪些 layoutId 自带图片位。 */
const describeImageSlotLayouts = (): string => {
  const byCount = new Map<number, string[]>()
  for (const layout of UNIVERSAL_LAYOUTS) {
    if (!(layout.imageCount > 0)) continue
    const ids = byCount.get(layout.imageCount) || []
    ids.push(layout.id)
    byCount.set(layout.imageCount, ids)
  }
  return [...byCount.entries()]
    .sort((left, right) => left[0] - right[0])
    .map(([count, ids]) => `${count} image slot(s): ${ids.join(', ')}`)
    .join('; ')
}

const buildImagePolicyPlanningGuidance = (imagePolicy?: ImagePolicy): string => {
  if (imagePolicy !== 'placeholder' && imagePolicy !== 'ai') return ''
  const mode =
    imagePolicy === 'placeholder'
      ? 'Images will render as replaceable placeholder frames (semantic image placeholders), not real photos.'
      : 'Images will be generated by an image model and filled into the planned slots.'
  return [
    'Image requirement (hard):',
    `- The user asked for an image-bearing deck. Image slots are only assigned to slides whose layoutId carries image slots; a text-only layoutId means this slide gets NO image at all.`,
    `- For content slides where a visual genuinely helps (character/product/scene/story/evidence pages), prefer an image-slot layoutId. Catalog image-slot layouts — ${describeImageSlotLayouts()}.`,
    `- Do not force every slide to be an image layout: keep cover/section/agenda/data pages text-first when that fits better, but at least half of the content slides should carry image slots when the user asks for images.`,
    `- ${mode}`
  ].join('\n')
}

const DECK_BACKGROUND_EDIT_RULE =
  'If a target page contains <img data-role="deck-background">, preserve that element, its src path, and its full-canvas bottom-layer positioning unless the user explicitly asks to replace or remove the PPT background.';

export function buildPlanningUserPrompt(args: {
  topic: string;
  totalPages: number;
  userMessage: string;
  hasSourceMaterials?: boolean;
  visualElementPreferences?: VisualElementPreferences;
  imagePolicy?: ImagePolicy;
}): string {
  const hasExplicitPageHint = /第\s*\d+\s*页|(?:page|slide)\s*\d+/i.test(args.userMessage);
  const sourcePlanningRules = args.hasSourceMaterials || hasSourceMaterialCue(args.userMessage)
    ? SOURCE_MATERIAL_PLANNING_RULES
    : "";
  const visualElementGuidance = args.visualElementPreferences
    ? formatVisualElementGuidance(args.visualElementPreferences)
    : "";
  const imagePolicyGuidance = buildImagePolicyPlanningGuidance(args.imagePolicy);
  return [
    `Topic: ${args.topic}`,
    `Target slide count: ${args.totalPages}`,
    `Return exactly ${args.totalPages} slides, no more and no fewer.`,
    hasExplicitPageHint ? "The user provided page/slide hints. Preserve that pagination intent when possible." : "",
    "",
    "Plan each slide title, key points, layout intent, and universal layout ID. Use short phrases, not long paragraphs.",
    sourcePlanningRules,
    visualElementGuidance,
    imagePolicyGuidance,
    "Output must be a JSON array. Each item must be exactly { title, keyPoints, layoutIntent, contentStructure, moduleCount, visualAspect, contentDensity, layoutId }; choose semantic structure and image geometry before a compatible catalog layoutId; layoutId is a catalog ID or null; keyPoints must contain 1-10 strings.",
    `The array length must be exactly ${args.totalPages}.`,
    "User requirements:",
    args.userMessage,
  ].join("\n");
}

export function buildDesignContractUserPrompt(): string {
  return [
    "Generate the unified visual contract only from the style specification in the system prompt.",
    "Do not use the topic, outline, or user requirements for content planning. The design contract is only for visual consistency.",
    "The theme field must describe visual mood, such as calm academic editorial or organic biophilic report. Do not turn it into the deck topic or a slide title.",
  ].join("\n");
}

export function buildEditUserPrompt(args: {
  userMessage: string;
  editScope?: DeckEditScope;
  selectedPageId?: string;
  selectedPageNumber?: number;
  selectedSelector?: string;
  elementTag?: string;
  elementText?: string;
  selectedElementContext?: SelectedElementRuntimeContext;
  existingPageIds?: string[];
}): string {
  const isContainerScope = args.editScope === "presentation-container";
  const isDeckScope = args.editScope === "deck";
  const selector = args.selectedSelector?.trim();

  if (isContainerScope) {
    return [
      "Apply the following edit instruction only to the presentation container:",
      "",
      args.userMessage,
      "",
      CONTENT_LANGUAGE_RULES,
      "",
      "Edit scope: presentation-container",
      "Target file: index.html",
      "Do not modify any /<pageId>.html files.",
      "Only set page transitions through set_index_transition(type, durationMs).",
      `Allowed type values: ${INDEX_TRANSITION_TYPES.join(", ")}. durationMs range: 120-1200, except none uses 0.`,
      args.existingPageIds?.length ? `Existing pages: ${args.existingPageIds.join(", ")}` : "",
    ].join("\n");
  }

  const elementDesc =
    args.elementTag
      ? `Target element: <${args.elementTag}>${args.elementText ? `"${args.elementText}"` : ""}`
      : "";

  return [
    isDeckScope
      ? "Apply the following edit instruction to the relevant /<pageId>.html files. You may edit multiple pages, but must not modify index.html:"
      : "Apply the following edit instruction only to the specified page content. Do not modify other pages:",
    "",
    args.userMessage,
    "",
    CONTENT_LANGUAGE_RULES,
    DECK_BACKGROUND_EDIT_RULE,
    "",
    args.selectedPageId
      ? `Target page: ${args.selectedPageId} (slide ${args.selectedPageNumber ?? "?"})`
      : isDeckScope
        ? "Target pages: all /<pageId>.html files relevant to the instruction"
        : "Target page: all pages",
    selector ? `Target element CSS selector: ${selector}` : "",
    elementDesc ? `Target element description: ${elementDesc}` : "",
    formatSelectedElementRuntimeContext(args.selectedElementContext),
    selector || elementDesc
      ? "Location and edit protocol:"
      : "",
    selector || elementDesc
      ? "- First use read_file to inspect the target page HTML source."
      : "",
    selector
      ? `- Search the source with grep for key selector parts such as classes or attributes: ${selector}`
      : "",
    elementDesc
      ? `- Search the source with grep for the element text: ${elementDesc}`
      : "",
    selector || elementDesc
      ? "- Use the selector and element text together to confirm the exact target node in the source."
      : "",
    selector || elementDesc
      ? "- Use edit_file(old_string, new_string) to modify the target node's HTML string directly."
      : "",
    selector || elementDesc
      ? "- old_string must be large enough to be unique in the file; new_string should contain only the modified portion."
      : "",
    selector || elementDesc
      ? "- Modify only the target node's text, classes, or local styles. Do not change surrounding structure."
      : "",
    selector || elementDesc
      ? "- Do not rewrite the whole page, drift unrelated styles, or perform broad global replacements."
      : "",
    !selector && !elementDesc
      ? "Edit strategy:"
      : "",
    !selector && !elementDesc
      ? "- If this is a local change, preserve the existing layout and update only the necessary local part."
      : "",
    !selector && !elementDesc
      ? "- If the user asks for relayout/redesign/restructure, you may rewrite the whole page fragment."
      : "",
    !selector && !elementDesc
      ? "- For full-page rewrites, follow the Stable HTML fragment protocol strictly. Do not rebuild the page shell."
      : "",
    !selector && !elementDesc ? STABLE_HTML_FRAGMENT_PROTOCOL : "",
    args.existingPageIds?.length ? `Existing pages: ${args.existingPageIds.join(", ")}` : "",
  ].join("\n");
}
